#!/bin/bash

# Get timestamp
ts=$(date +"%Y-%m-%d-%H-%M")

# Make filename
filename=$ts

# Paths to Obsidian vault and backup location
topath="/home/$(whoami)/OneDrive/Backups/"
frompath="/home/$(whoami)/Obsidian/"

# Create backup
tar -czf $topath$filename.tar.gz $frompath
